
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL
 */
public class BillPrint extends javax.swing.JFrame {

    /**
     * Creates new form BillPrint
     */
      Connection con=connect.Connection();
       Statement st=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
 
    String billid=BillDetails.id;
     String roomnumber;
    String name;
    String mobile;
   
     String bed; 
     String nationality;     
        
    String roomtype; 
    String date;
    String outdate;
    String price;
    String days;
    String  amount;       
            
    public BillPrint() {
        initComponents();
        connect();
       
      
        txtbill.setText("\t\t-:Hotet Management:-\n");
        txtbill.setText(txtbill.getText()+"************************************* \n");
         
     txtbill.setText(txtbill.getText()+"Bill ID:-"+billid+" \n");
        System.out.println("\n");
        txtbill.setText(txtbill.getText()+" Customer Details:-\n");
        txtbill.setText(txtbill.getText()+"name:-"+name+"\n");
       txtbill.setText(txtbill.getText()+"Mobile Number:-"+mobile+"\n");
        txtbill.setText(txtbill.getText()+"Nationality:-\n"+nationality+"\n");
        txtbill.setText(txtbill.getText()+"Room Details:-\n");
        txtbill.setText(txtbill.getText()+"Room Number:-"+roomnumber+"\n");
        txtbill.setText(txtbill.getText()+"Room Type:-"+roomtype+"\n");
        txtbill.setText(txtbill.getText()+"Bed:-"+bed+"\n");
        txtbill.setText(txtbill.getText()+"Price:-"+price+"\n");
        txtbill.setText(txtbill.getText()+"\nCheck in Date:-"+date+"\n");
        txtbill.setText(txtbill.getText()+"Check out Date:-"+outdate+"\n");
        txtbill.setText(txtbill.getText()+"Number of Days:-"+days+"\n");
        txtbill.setText(txtbill.getText()+"\nAmount:-"+amount+"\n");
        txtbill.setText(txtbill.getText()+"*************************************\n");
        txtbill.setText(txtbill.getText()+"\t\t"+"Thank You, Please Visite Again");
    }
    public void connect(){
        
        
        try {
            pst=con.prepareStatement("select*from customer1 where billid=?");
            pst.setString(1,billid);
            rs=pst.executeQuery();
            if(rs.next()){
                name=rs.getString("name");
                 
     billid=rs.getString("billid");
     roomnumber=rs.getString("roomnumber");
     name=rs.getString("name");
     mobile=rs.getString("mobile");
      bed=rs.getString("bed");
    nationality=rs.getString("nationality");
    roomtype =rs.getString("roomtype");
    date=rs.getString("date");
     outdate=rs.getString("outdate");
     price=rs.getString("price");
    days=rs.getString("days");
      amount=rs.getString("amount");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillPrint.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbill = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbill.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 51, 680, 480));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h5.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 48, 39));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 97, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try {
              // TODO add your handling code here:
              txtbill.print();
          } catch (PrinterException ex) {
              Logger.getLogger(BillPrint.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtbill;
    // End of variables declaration//GEN-END:variables
}
