
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
     Connection con=connect.Connection();
       Statement st=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
    public Checkout() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("YYYY-MM-dd");
        Date date=new Date();
        txtoutdate.setText(obj.format(date));
        ShowRecordInTable();
    }
  public void ShowRecordInTable(){
        
        try  {//pst=con.prepareStatement("select status from customer1 where status=?");
          // pst.setString(1,"null");
            pst=con.prepareStatement("select * from customer1 where status=?");
        pst.setString( 1,"NULL");
            rs=pst.executeQuery();
            ResultSetMetaData rsmd=rs.getMetaData();
          int  c=rsmd.getColumnCount();
            DefaultTableModel DModel=(DefaultTableModel) jTable1.getModel();
            DModel.setRowCount(0);
            while(rs.next()){
                Vector column=new Vector();
                for(int i=1;i<=c;i++){
                    
                    column.add(rs.getString("name"));
                    column.add(rs.getString("mobile"));
                    column.add(rs.getString("id"));
                    column.add(rs.getString("roomnumber"));
                    column.add(rs.getString("bed"));
                    column.add(rs.getString("roomtype"));
                    column.add(rs.getString("date"));
                   // column.add(rs.getString("outdate"));
                  //column.add(rs.getString("price"));
                 column.add(rs.getString("price"));
                    column.add(rs.getString("nationality"));
                    
                    
                }
                DModel.addRow(column);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtroomnumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtadhar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtdays = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btncheck = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtoutdate = new javax.swing.JTextField();
        txtindate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/out.jpg"))); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 6, 239, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 50, 120, 29));

        txtroomnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtroomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroomnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 44, 71, 40));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 45, 94, 40));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 103, 134, 28));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 103, 134, 28));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adhar Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 108, 103, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 142, 250, 42));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 143, 250, 40));

        txtadhar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 142, 249, 42));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Price per Day");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 195, 89, 25));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of Days");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 195, 165, 25));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(948, 198, 109, 18));

        txtprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 231, 250, 44));

        txtdays.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaysActionPerformed(evt);
            }
        });
        getContentPane().add(txtdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 231, 250, 44));

        txtamount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 231, 249, 44));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Check in Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 286, 110, 31));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Check out Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 132, 20));

        btncheck.setBackground(new java.awt.Color(204, 0, 0));
        btncheck.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btncheck.setForeground(new java.awt.Color(255, 255, 255));
        btncheck.setText("Check out Now");
        btncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckActionPerformed(evt);
            }
        });
        getContentPane().add(btncheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 324, -1, 44));

        btnclear.setBackground(new java.awt.Color(204, 0, 0));
        btnclear.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 324, -1, 44));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Mobile Number", "Adhar Number", "Room Number", "Bed Type", "Room Type", "Check in Date", "Price per Day", "Nationality"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 394, 1150, 410));

        txtoutdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 323, 250, 44));

        txtindate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtindate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtindateActionPerformed(evt);
            }
        });
        getContentPane().add(txtindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 323, 250, 44));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h5.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1176, 0, 64, 52));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtroomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroomnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroomnumberActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckActionPerformed
        
        if(txtname.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Please Enter Room Number And Search it,Then check out Customer");
        
        try {
             // TODO add your handling code here:
             pst=con.prepareCall("update customer1 set status=?where roomnumber=? and date=?");
             pst.setString(1,"Check-Out");
             pst.setString(2, txtroomnumber.getText());
            pst.setString(3, txtindate.getText());
             pst.executeUpdate();
             
             pst=con.prepareStatement("update customer1 set amount=?,outdate=?,days=? where roomnumber=? and date=?");
             pst.setString(1, txtamount.getText());
              pst.setString(2, txtoutdate.getText()); 
              pst.setString(3, txtdays.getText());
               pst.setString(4, txtroomnumber.getText());
               
                pst.setString(5, txtindate.getText());
                pst.executeUpdate();
               pst=con.prepareCall("update room set status=?where roomnumber=?");
                pst.setString(1,"Not-Booked");
             pst.setString(2, txtroomnumber.getText());
               pst.executeUpdate();
            int yes= JOptionPane.showConfirmDialog(this,"Check out Successfully","Check outed",JOptionPane.YES_NO_OPTION);
            if(JOptionPane.YES_OPTION==yes)
              // new BillDetials.setVistible(true);
                new BillDetails().setVisible(true);  
             ShowRecordInTable();
              txtname.setText("");
        txtmobile.setText("");
        txtadhar.setText("");
        txtprice.setText("");
        txtdays.setText("");
        txtindate.setText("");
        
    //   txtoutdate.setText("");
        txtamount.setText("");
        
             
             
         } catch (SQLException ex) {
             Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btncheckActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // if(txtroomnumber.getText().equals(""))
            
        
        try {
             // TODO add your handling code here:
             pst=con.prepareStatement("select * from customer1 where roomnumber=? and status=? ");
             pst.setString(1, txtroomnumber.getText());
             // pst=con.prepareStatement("select status from customer1 where status=? ");
           pst.setString(2, "NULL");
             rs=pst.executeQuery();
             if(rs.next()){
                 txtname.setText(rs.getString("name"));
                  txtmobile.setText(rs.getString("mobile"));
                   txtadhar.setText(rs.getString("id"));
                    txtprice.setText(rs.getString("price"));
                     txtindate.setText(rs.getString("date"));
                      
             }
             String s1,s2;
             s1=txtoutdate.getText();
            // s2=rs.getString("date");
             SimpleDateFormat formate=new SimpleDateFormat("yyyy-MM-dd");
             s2=rs.getString("date");
             Date d1=formate.parse(s1);
             Date d2=formate.parse(s2);
             long diff=d1.getTime()-d2.getTime();
             int days=(int)diff/(24*60*60*1000);
             if(days==0)
                 days=1;
             txtdays.setText(String.valueOf(days));
             double price=Double.parseDouble(rs.getString("price"))*days;
             txtamount.setText(String.valueOf(price));
             
             
             
             
             
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
         } 
         catch (ParseException ex) {
             Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
             
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtmobile.setText("");
        txtadhar.setText("");
        txtprice.setText("");
        txtdays.setText("");
        txtindate.setText("");
        //txtoutdate.setText("");
        txtamount.setText("");
        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaysActionPerformed

    private void txtindateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtindateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtindateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheck;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtadhar;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtindate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtoutdate;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomnumber;
    // End of variables declaration//GEN-END:variables

   // private void initComponents() {
   //     throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  //  }
 private static class rsmd {

        private static int getColumnCount() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public rsmd() {
        }
    }
}

