
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RAHUL
 */
public final class CustomerChekin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerChekin
     */
    Connection con=connect.Connection();
        PreparedStatement pst=null;
        ResultSet rs=null;
        Statement st=null;
        
        
    public CustomerChekin() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("YYYY-MM-dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
      //  txtname.requestFocus();
        
        seema();
    }
    
    public void seema(){
         try {
             pst=con.prepareStatement("select roomnumber from room  where bed=? and roomtype=? and status=?");
             pst.setString(1,combobed.getItemAt(combobed.getSelectedIndex()));
             pst.setString(2,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
             pst.setString(3,"Not-Booked");
             rs=pst.executeQuery();
           comboroomnumber.removeAllItems();
         while(rs.next()){
            comboroomnumber.addItem(rs.getString("roomnumber"));
             
         }
         pst=con.prepareStatement("Select price from room where roomnumber=?");
        pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
         rs=pst.executeQuery();
         if(rs.next())
            txtprice.setText(rs.getString("price"));
           // pst.setString(3,combobed.getItemAt(combobed.getSelectedIndex()));
         } catch (SQLException ex) {
             Logger.getLogger(CustomerChekin.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtadhar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combobed = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        comboroomnumber = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cus.png"))); // NOI18N
        jLabel1.setText("Customer Chekin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 6, 206, 81));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h5.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 59, 44));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 93, 142, 29));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 151, 237, 39));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 219, 152, 30));

        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 278, 237, 39));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 346, 208, 34));

        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other" }));
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 409, 237, 39));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nationality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 477, 203, 31));

        txtnat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnatActionPerformed(evt);
            }
        });
        getContentPane().add(txtnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 537, 237, 39));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adhar Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 605, 197, 30));

        txtadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadharActionPerformed(evt);
            }
        });
        getContentPane().add(txtadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 664, 237, 39));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check in Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 93, 223, 29));

        txtdate.setEditable(false);
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 151, 238, 39));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bed Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 219, 212, 30));

        combobed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        combobed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedItemStateChanged(evt);
            }
        });
        combobed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobedActionPerformed(evt);
            }
        });
        getContentPane().add(combobed, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 238, 39));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Room Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 346, 228, 34));

        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC" }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        comboroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboroomtypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 409, 238, 39));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 477, 238, 31));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 605, 238, 30));

        txtprice.setEditable(false);
        txtprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpriceMouseClicked(evt);
            }
        });
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 664, 238, 39));

        btncheckin.setBackground(new java.awt.Color(204, 0, 0));
        btncheckin.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btncheckin.setForeground(new java.awt.Color(255, 255, 255));
        btncheckin.setText("Check in Now");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 719, 123, 55));

        btnclear.setBackground(new java.awt.Color(204, 0, 0));
        btnclear.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 719, 101, 55));

        comboroomnumber.setMaximumRowCount(90);
        comboroomnumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomnumberItemStateChanged(evt);
            }
        });
        comboroomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboroomnumberActionPerformed(evt);
            }
        });
        getContentPane().add(comboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 240, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO ad your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnatActionPerformed

    private void txtadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadharActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpriceActionPerformed

    private void combobedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobedActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
        txtname.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
        }
            else if(txtmobile.getText().equals("")){
        txtmobile.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required"); 
        }
          else if(txtadhar.getText().equals("")){
        txtadhar.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required"); 
        }
          else if(txtnat.getText().equals("")){
        txtnat.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required"); 
           
        
        }
          else{
              
            try {
            // Connection con=connect.Connection();
          // pst=con.prepareStatement("insert into customer(roomnumber,roomtype,bed,price,status)values(?,?,?,?,?)");
             //pst=con.prepareStatement("insert into customer1(name,mobile,gender,id,nationality,indate,roomnumber,roomtype,bed,pricr,status)values(?,?,?,?,?,?,?,?,?,?,?)");
             pst=con.prepareStatement("insert into customer1(name,mobile,gender,id,nationality,roomnumber,date,roomtype,bed,price,status)values(?,?,?,?,?,?,?,?,?,?,?)");
       //  pst=con.prepareStatement("update into customer1 name=?");
          pst.setString(1, txtname.getText());
             pst.setString(2, txtmobile.getText());
              pst.setString(3, combogender.getItemAt(combogender.getSelectedIndex()));
               pst.setString(4, txtadhar.getText());
                pst.setString(5, txtnat.getText());
                 pst.setString(7, txtdate.getText());
                  pst.setString(6, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
                   pst.setString(8, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
                    pst.setString(9, combobed.getItemAt(combobed.getSelectedIndex()));
                     pst.setString(10, txtprice.getText());
                      pst.setString(11, "NULL");
                    pst.executeUpdate();
                      JOptionPane.showMessageDialog(this,"Customer Check in Successfully");
                      
                        //  txtname.setText("");
       // txtadhar.setText("");
       // txtmobile.setText("");
       // txtnat.setText("");
      //txtdate.setText("");
       // txtprice.setText("");
      /*  combobed.setSelectedIndex(0);
        combogender.setSelectedIndex(0);
        comboroomtype.setSelectedIndex(0);
        if(comboroomnumber.getItemCount()==0);
        txtprice.setText("");*/
                      pst=con.prepareStatement("update room set status=? where roomnumber=? ");
                      pst.setString(1, "Booked");
                      pst.setString(2, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
                      pst.executeUpdate();
                      seema();
                      
                          txtname.setText("");
        txtadhar.setText("");
        txtmobile.setText("");
        txtnat.setText("");
                //      txtprice.setText("");
        // try {
         /*    pst=con.prepareStatement("select roomnumber from room  where bed=? and roomtype=? and status=?");
             pst.setString(1,combobed.getItemAt(combobed.getSelectedIndex()));
             pst.setString(2,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
             pst.setString(3,"Not-Booked");
             rs=pst.executeQuery();
            comboroomnumber.removeAllItems();
         while(rs.next()){
            comboroomnumber.addItem(rs.getString("roomnumber"));
             
         }
         pst=con.prepareStatement("Select price from room where roomnumber=?");
        pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
         rs=pst.executeQuery();
         if(rs.next())
            txtprice.setText(rs.getString("price"));
           // pst.setString(3,combobed.getItemAt(combobed.getSelectedIndex()));
         } catch (SQLException ex) {
             Logger.getLogger(CustomerChekin.class.getName()).log(Level.SEVERE, null, ex);
         }
            */         
            
            } catch (SQLException ex) {
                Logger.getLogger(CustomerChekin.class.getName()).log(Level.SEVERE, null, ex);
            }
              
              
          }
    }//GEN-LAST:event_btncheckinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboroomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeActionPerformed

    private void combobedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedItemStateChanged
        // TODO add your handling code here:
       seema();
    }//GEN-LAST:event_combobedItemStateChanged

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
        // TODO add your handling code here:
     seema();
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void comboroomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboroomnumberActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_comboroomnumberActionPerformed

    private void comboroomnumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomnumberItemStateChanged
        // TODO add your handling code here:
  
    }//GEN-LAST:event_comboroomnumberItemStateChanged

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtadhar.setText("");
        txtmobile.setText("");
        txtnat.setText("");
      //  txtdate.setText("");
       // txtprice.setText("");
       // combobed.setSelectedIndex(0);
       // combogender.setSelectedIndex(0);
      //  comboroomtype.setSelectedIndex(0);
      //  if(comboroomnumber.getItemCount()==0);
      //  txtprice.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtpriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpriceMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpriceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerChekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerChekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerChekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerChekin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new CustomerChekin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> combobed;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomnumber;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtadhar;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnat;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
